//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BranchMaster
    {
        public long BranchCode { get; set; }
        public long BankCode { get; set; }
        public string BranchName { get; set; }
        public string MICR_Code { get; set; }
        public string IFSC_Code { get; set; }
        public Nullable<long> Contact { get; set; }
        public string Fax { get; set; }
        public string EmailID { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string Address { get; set; }
        public Nullable<long> PinCode { get; set; }
    
        public virtual BankMaster BankMaster { get; set; }
    }
}
