//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CastMaster
    {
        public long CastCode { get; set; }
        public long ReligionID { get; set; }
        public string CastName { get; set; }
    
        public virtual ReligionMaster ReligionMaster { get; set; }
    }
}
