//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Personal_Detail
    {
        public long ID { get; set; }
        public long Gender { get; set; }
        public System.DateTime DOB { get; set; }
        public long Category { get; set; }
        public string IdentityMark1 { get; set; }
        public string IdentityMark2 { get; set; }
        public Nullable<long> Religion { get; set; }
        public Nullable<long> Citizenship { get; set; }
        public Nullable<long> Caste { get; set; }
        public string Race { get; set; }
        public Nullable<long> MarraigeStatus { get; set; }
        public Nullable<System.DateTime> MarraigeDate { get; set; }
        public Nullable<int> NoOfChild { get; set; }
        public Nullable<int> NoOfDependents { get; set; }
        public Nullable<decimal> AadharNo { get; set; }
        public Nullable<decimal> SIN { get; set; }
        public string AKA { get; set; }
        public string MilitaryService { get; set; }
        public string BirthCity { get; set; }
        public string Note { get; set; }
        public string Hobbies { get; set; }
        public string MilitaryServiceDetail { get; set; }
        public Nullable<long> EmployeeID { get; set; }
    
        public virtual CastMaster CastMaster { get; set; }
        public virtual HRMS_CATEGORY_GRADE HRMS_CATEGORY_GRADE { get; set; }
        public virtual HRMS_EMP_CITIZENSHIP_MS HRMS_EMP_CITIZENSHIP_MS { get; set; }
        public virtual HRMS_EMP_GENDER_MS HRMS_EMP_GENDER_MS { get; set; }
        public virtual MaritalMaster MaritalMaster { get; set; }
        public virtual ReligionMaster ReligionMaster { get; set; }
    }
}
