//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRMS_EMP_BANK_BRANCH_MS
    {
        public long Bank_Branch_Code { get; set; }
        public long Bank_Code { get; set; }
        public string Bank_Branch_Name { get; set; }
        public long Bank_Branch_MICR_Code { get; set; }
        public long Bank_Branch_IFSC_Code { get; set; }
        public long Bank_Branch_Contact_NO { get; set; }
        public long Bank_Branch_Fax_NO { get; set; }
        public string Bank_Branch_Email_ID { get; set; }
        public string Bank_Branch_Address { get; set; }
        public string Bank_Branch_Country { get; set; }
        public string Bank_Branch_State { get; set; }
        public long Bank_Branch_PinCode { get; set; }
    
        public virtual HRMS_EMP_BANK_MS HRMS_EMP_BANK_MS { get; set; }
    }
}
