//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRMS_Emp_Details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HRMS_Emp_Details()
        {
            this.HRMS_EMP_PHOTO_SIGN = new HashSet<HRMS_EMP_PHOTO_SIGN>();
        }
    
        public long Emp_ID { get; set; }
        public long Emp_Cd { get; set; }
        public Nullable<long> Old_Emp_Cd { get; set; }
        public System.DateTime Join_Date { get; set; }
        public Nullable<long> Card_Id { get; set; }
        public long salutation { get; set; }
        public string First_Name { get; set; }
        public string Middle_Name { get; set; }
        public string Last_Name { get; set; }
        public string Display_Name { get; set; }
        public long Designation { get; set; }
        public Nullable<long> Work_Location { get; set; }
        public long Unit { get; set; }
        public long Department { get; set; }
        public long Cost_Center { get; set; }
        public Nullable<long> UAN_No_ { get; set; }
    
        public virtual HRMS_COST_CENTER HRMS_COST_CENTER { get; set; }
        public virtual HRMS_DEPT HRMS_DEPT { get; set; }
        public virtual HRMS_EMP_DESIGNATION_MS HRMS_EMP_DESIGNATION_MS { get; set; }
        public virtual HRMS_SALUTATION HRMS_SALUTATION { get; set; }
        public virtual UnitMaster UnitMaster { get; set; }
        public virtual WorkLocationMaster WorkLocationMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRMS_EMP_PHOTO_SIGN> HRMS_EMP_PHOTO_SIGN { get; set; }
    }
}
