//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HRMSEntities : DbContext
    {
        public HRMSEntities()
            : base("name=HRMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HRMS_ATTACHMENT_TYPE> HRMS_ATTACHMENT_TYPE { get; set; }
        public virtual DbSet<HRMS_CATEGORY_GRADE> HRMS_CATEGORY_GRADE { get; set; }
        public virtual DbSet<HRMS_SALUTATION> HRMS_SALUTATION { get; set; }
        public virtual DbSet<HRMS_COST_CENTER> HRMS_COST_CENTER { get; set; }
        public virtual DbSet<HRMS_DEPT> HRMS_DEPT { get; set; }
        public virtual DbSet<CastMaster> CastMasters { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<HRMS_EMP_BUSINESSDIVISION_MS> HRMS_EMP_BUSINESSDIVISION_MS { get; set; }
        public virtual DbSet<HRMS_EMP_CITIZENSHIP_MS> HRMS_EMP_CITIZENSHIP_MS { get; set; }
        public virtual DbSet<HRMS_EMP_DESIGNATION_MS> HRMS_EMP_DESIGNATION_MS { get; set; }
        public virtual DbSet<HRMS_EMP_GENDER_MS> HRMS_EMP_GENDER_MS { get; set; }
        public virtual DbSet<MaritalMaster> MaritalMasters { get; set; }
        public virtual DbSet<PayRollMaster> PayRollMasters { get; set; }
        public virtual DbSet<ReligionMaster> ReligionMasters { get; set; }
        public virtual DbSet<SegmentMaster> SegmentMasters { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<UnitMaster> UnitMasters { get; set; }
        public virtual DbSet<WorkLocationMaster> WorkLocationMasters { get; set; }
        public virtual DbSet<BankMaster> BankMaster { get; set; }
        public virtual DbSet<BranchMaster> BranchMaster { get; set; }
        public virtual DbSet<Employee_Personal_Detail> Employee_Personal_Detail { get; set; }
        public virtual DbSet<HRMS_EMP_BANK_BRANCH_MS> HRMS_EMP_BANK_BRANCH_MS { get; set; }
        public virtual DbSet<HRMS_EMP_BANK_MS> HRMS_EMP_BANK_MS { get; set; }
        public virtual DbSet<HRMS_Emp_Details> HRMS_Emp_Details { get; set; }
        public virtual DbSet<HRMS_EMP_PHOTO_SIGN> HRMS_EMP_PHOTO_SIGN { get; set; }
    }
}
