//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRMS_EMP_BUSINESSDIVISION_MS
    {
        public long BusinessDivision_ID { get; set; }
        public string BusinessDivision_Name { get; set; }
        public Nullable<long> BusinessDivision_SapCode { get; set; }
    }
}
