//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRMS_CATEGORY_GRADE
    {
        public long Category_ID { get; set; }
        public string Category_Name { get; set; }
        public string Grade_Name { get; set; }
        public string Grade_Detail { get; set; }
    }
}
