//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRMS_EMP_PHOTO_SIGN
    {
        public long Emp_Photo_ID { get; set; }
        public long Emp_ID { get; set; }
        public byte[] Emp_Image { get; set; }
        public byte[] Emp_Signature { get; set; }
    
        public virtual HRMS_Emp_Details HRMS_Emp_Details { get; set; }
    }
}
