//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRMS_EMP_BANK_MS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HRMS_EMP_BANK_MS()
        {
            this.HRMS_EMP_BANK_BRANCH_MS = new HashSet<HRMS_EMP_BANK_BRANCH_MS>();
        }
    
        public long Bank_Code { get; set; }
        public string Bank_Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRMS_EMP_BANK_BRANCH_MS> HRMS_EMP_BANK_BRANCH_MS { get; set; }
    }
}
