//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRMS_COST_CENTER
    {
        public long ID { get; set; }
        public long Cost_Cntr_Code { get; set; }
        public string Cost_Cntr_Name { get; set; }
        public Nullable<long> Parent_Cost_Cntr_Code { get; set; }
        public Nullable<long> Ledger_Code { get; set; }
    }
}
