//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitMaster
    {
        public long UnitCode { get; set; }
        public string UnitName { get; set; }
        public string Address { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public long Pincode { get; set; }
        public long Priority { get; set; }
        public bool PaySlip { get; set; }
        public bool IsActive { get; set; }
        public string State { get; set; }
    }
}
